//! `SeaORM` Entity, @generated by sea-orm-codegen 1.0.1

pub use super::followers::Entity as Followers;
pub use super::impressions::Entity as Impressions;
pub use super::otakiages::Entity as Otakiages;
pub use super::posts::Entity as Posts;
pub use super::users::Entity as Users;
